### ISSUE TITLE
Migration to version 13.0

### ISSUE THREAD

**Issue by jjscarafia** [ingadhoc/website#146]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

# Modules to migrate

- [ ] payment_mercadopago
- [ ] payment_todopago
- [ ] website_sale_ux
- [ ] l10n_ar_website_sale_delivery
- [ ] website_product_pack
- [ ] website_sale_wishlist_ux
- [ ] website_sale_promotion
- [ ] l10n_ar_website_sale
- [ ] website_sale_search_improved
- [ ] website_product_attribute_link
- [ ] website_sale_stock_ux
- [ ] website_security
- [ ] website_sale_product_description
- [ ] website_doc
- [ ] website_sale_order_type

**Comment by foxcarlos** [comment]
Hola instale el modulo payment_mercadopago par ala version 13 pero me indica los siguientes errores:

- @api.multi no existe en odoo.api

- self.environment no existe en el model payment_acquirer.py

- No existe  el campo "error_msg" en el model , esto esta declarado en la vista payment_mercadopago/data/payment_acquirer_data.xml

**Comment by jjscarafia** [comment]
Buenas @foxcarlos . Gracias por reportar:
1. el módulo de mercadopago todavía no está migrado, por eso se marca como [installable False](https://github.com/ingadhoc/website/blob/13.0/payment_mercadopago/__manifest__.py#L43)
2. este ticket es para dar seguimiento a tareas de migración de modulos, para reporte de errores y demás por favor crear un nuevo ticket, igualmente esto no es un error en si, es simplemente que todavía no está migraado.
3. bienvenidos PRs migrando el módulo, igual creo que alguien estaba por hacer un pr con este módulo

Saludos!

**Comment by foxcarlos** [comment]
Muchas gracias, yo hice los cambios y ahora ya me funciona bien, pero no estaba seguro si era bienvenido los cambios
