### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by adhoc-transbot** [ingadhoc/website#56]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] l10n_ar_website_sale
- [ ] payment_force_other_currency
- [ ] payment_mercadopago
- [ ] payment_todopago
- [ ] website_doc
- [ ] website_portal_usability
- [ ] website_product_attribute_link
- [ ] website_product_pack
- [ ] website_project_issue_solution
- [ ] website_project_task
- [ ] website_sale_clear_line
- [ ] website_sale_custom_search
- [ ] website_sale_delivery_taxes_included
- [ ] website_sale_note
- [ ] website_sale_order_type
- [ ] website_sale_product_description
- [ ] website_sale_promotion
- [ ] website_sale_search_improved
- [ ] website_sale_taxes_included
- [ ] website_sale_usability
- [ ] website_security
- [ ] website_talkus
